### ISSUE TITLE
Update to BigSur

### ISSUE THREAD

**Issue by kniffo84** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#1]
Hi Marcell,

as first thank you so much for your guide it is very cool. It works great under Catalina.
I have an I5 4590 with 4GB Ram and 240 GB SSD.

But if I want to install the update BigSur starts to update, after 15 min they want to reboot but instead to reboot I come to the screen for sign in...

Did you know that problem?

**Comment by varszegimarcell** [comment]
Hello

It is coming back to Catalina login screen?

Once I've succeeded with the update method, but at the time, the OS was so buggy, that I decided to roll back to Catalina.

I encountered once the same issue, but I thought it happened because corrupt Big Sur installation files. I've made an USB with gibMacOS on an antoher machine, and then I did a clean install. 

If you cannot resolve the issue, I recommend to make a Time Machine backup on a spare disk, format your SSD, do a clean install, and then restore your data from the Time Machine backup, on the first boot setup program. It should work. 

Let me know how it goes. :)

Cheers
M

**Comment by kniffo84** [comment]
How I can create an BigSur installer Stick? If I use GibMaster I can download the files but it is not possible with Makeinstall to create the stick. They don't find the file. Do I have to change the file name in BigSur ?

**Comment by varszegimarcell** [comment]
Ohhh I see whats the problem. For Big Sur, I probably did not used gibMacOS, and my memories were wrong about that.

Download Big Sur from the app store, like you would on a real mac, and make an installer disk like that. 

I did not knew that gibMacOS is broken with Big Sur, I gonna open a new issue on their repo. Thanks for letting me know about that!

**Comment by varszegimarcell** [comment]
You've got results like this, am I alright?

![Képernyőfotó 2020-11-16 - 23 51 02](https://user-images.githubusercontent.com/47447944/99317655-b26a0580-2866-11eb-9f19-bb8b473ebaea.png)
![Képernyőfotó 2020-11-16 - 23 51 18](https://user-images.githubusercontent.com/47447944/99317664-b4cc5f80-2866-11eb-9392-2e1fd89ce563.png)

**Comment by varszegimarcell** [comment]
Here's the issue I've opened: https://github.com/corpnewt/gibMacOS/issues/194

**Comment by varszegimarcell** [comment]
Also, I've updated the guide, to mention these problems that just turned out to be problems not just for me.

**Comment by kniffo84** [comment]
Cool thanks 👍
