### ISSUE TITLE
screen wont come back on after turned off

### ISSUE THREAD

**Issue by tylermmoore** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#14]
Mostly working. I have 3020m with i5 4590t and if the screen goes off I cant get it to come back on. The computer is still on as i can SSH into it etc but the screen (via DP) wont wake unless i reboot. Any ideas?

**Comment by Caibuk** [comment]
Let me first thank you @varszegimarcell very much for this great guide and customized EFI folder! 

I have the exact same system and setup (Optiplex 3020m, i5-4590t, Dell Monitor connected via DP) and sadly the same issue. The screen wakes up after going to sleep for two or three seconds and then turns - and stays - black afterwards.
I disabled monitor sleep as a workaround and use hibernate as wake from hibernate works flawlessly.

Thanks in advance for any indication how to solve this inconvenience.

**Comment by Caibuk** [comment]
As mentioned in #15 I made an USBmap specifically for my 3020m following the dortania guide
- here https://dortania.github.io/OpenCore-Post-Install/usb/system-preparation.html and
- here https://dortania.github.io/OpenCore-Post-Install/usb/intel-mapping/intel.html.

After
- building and adding my own `USBMap.kext` to `/EFI/OC/Kexts`,
- deleting `USBInjectAll.kext`,
- setting `XhciPortLimit` to `false` in `config.plist`,
- running `OC Clean Snapshot` in ProperTree
- and rebooting

my monitor seems to go to sleep and get woken up with no problem whatsoever.

I'd suggest you give it a try too.

**Comment by varszegimarcell** [comment]
Hey guys!

Thank you for your feedback! I will definitely check out this issue, and I will add a custom USB map to these machines. 

Can you please upload the USBMap.kext for the 3020M? I have only a 3020SFF, which is technically the same machine as the 3020MT. The 3020M is a slightly different beast, which I do not have sadly.

**Comment by Caibuk** [comment]
Sorry for the delay.
Here it is:
[USBMap.kext.zip](https://github.com/varszegimarcell/Optiplex-3020-Hackintosh-OpenCore/files/6180017/USBMap.kext.zip)

**Comment by varszegimarcell** [comment]
> Sorry for the delay.
> Here it is:
> [USBMap.kext.zip](https://github.com/varszegimarcell/Optiplex-3020-Hackintosh-OpenCore/files/6180017/USBMap.kext.zip)

No problem! I am quite busy at the moment too, as my university duties just started to kick me in the ass... :D

**Comment by Kinetik** [comment]
Hi. I did the mapping for the SFF and, it's true, the monitor powers on correctly after sleep.
Here is the kext: 
[USBMap.kext.zip](https://github.com/varszegimarcell/Optiplex-3020-Hackintosh-OpenCore/files/6239620/USBMap.kext.zip)

1. replace USBinjectall.kext with USBMap.kext
2. remove in plist   Kernel->Add->7       (this is the USBinjectall entry, we do not need an entry for the USBMap)
3. change in plist Kernel->Quirks->XhciportLimit to False
4. save and reboot

This solves part of the issue, it still does not enable the 2xUSB3.0 ports, but when I will have time I will research a bit more.

Description:
- we have 8 USB ports (2x3.0 and 6x2.0)
- USBinjectall discovers instead of 8 ports, it reads 12  (2x3.0 and 10x2.0).  Ads 4 more dummy(or whatever)
- what I did basically is remove those extra 4 
- I set them all as 3.0, but is seems that all 8 were taken as 2.0
- no difference from what is was initially, but monitor control is back at least.

**Comment by Kinetik** [comment]
Hi. I just re-checked. The 3.0 ports on the back work correctly. I was looking in the wrong place for the changes.
So, all good :)
