### ISSUE TITLE
Zotac GT 730 LP & Sound

### ISSUE THREAD

**Issue by zabrikat** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#16]
Hello there,

what can I do to use my backside aux? The sound only comes from internal inside soundboard, the front aux is working.

And can you tell me how to get the zotac gt 730 lp usable? 

Thanks a lot in advance!

**Comment by varszegimarcell** [comment]
Hello!

An another user reported this issue to me a few days, before you, and the issue exist for me too. We'll need probably a different AppleALC layout-id, sadly at the moment, I had no time to investigate the issue due to my university studies. I am aware of the issue, and I want to fix this as soon as possible. 

I link the issue, so you can check its progress out: https://github.com/varszegimarcell/Optiplex-3020-Hackintosh-OpenCore/issues/12

Well, about the GPU, I found this on [Dortania's GPU Buyers Guide](https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/nvidia-gpu.html#kepler-series-gtx-6xx-7xx)

![Képernyőfotó 2021-03-22 - 14 25 19](https://user-images.githubusercontent.com/47447944/111996563-70a1e200-8b1a-11eb-985b-a9de4faa7908.png)

You have to check what kind of GPU chip you have in your GT730, as it turns out, not all GT730 card are supported. 

After that, you have to put your iGPU into encode only mode, I've wrote a section about it in my guide. In case of the GT730, you don't need any specific tweaks to make the dGPU work, drivers included in the OS. It is recommended to add the 
    shikigva=40
boot flag into your config.plist.
![Képernyőfotó 2021-03-22 - 14 37 37](https://user-images.githubusercontent.com/47447944/111998289-2883bf00-8b1c-11eb-87b9-33cde3c5882a.png)
You can access the boot-args here.
