### ISSUE TITLE
Nvidia Drivers

### ISSUE THREAD

**Issue by PringlePot** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#67]
Is there any way I could use my nvidia card while installing? I don't have a displayport display sadly

**Comment by Xtendera** [comment]
Hello @PringlePot,

Nvidia Support is complex and not many GPUs are supported. This guide does not cover using Nvidia GPUs just because of the small amount of users using a GPU on this computer. Here are the GPUs supported on the Dortania install guide:
https://dortania.github.io/OpenCore-Install-Guide/macos-limits.html#gpu-support

To use GPUs, you will have to read through the guide as I do not even own a GPU of any kind.

Thanks,
@Xtendera
